-- generated by tools/gen_glue_data.py (mode coa); do not edit
ASC_CREATE_MODE = "coa"
-- the chooser shows only on these realms (GetServerName() in glue); elsewhere the stock screen stands
ASC_CREATE_COA_REALMS = { ["Conquest of Azeroth"] = true }
ASC_CREATE_TEXTURE = "Interface\\Glues\\CHARACTERCREATE\\UI-CHARACTERCREATE-CLASSES"
ASC_CREATE_CLASSES = {
    { byte = 12, token = "BARBARIAN", name = "Barbarian", power = 3, carriers = {4}, coords = {0.000000, 0.125000, 0.000000, 0.250000}, specs = "Headhunting, Brutality, Ancestry" },
    { byte = 20, token = "SONOFARUGAL", name = "Bloodmage", power = 1, carriers = {1}, coords = {0.625000, 0.750000, 0.500000, 0.750000}, specs = "Fleshweaver, Sanguine, Accursed, Eternal" },
    { byte = 22, token = "CHRONOMANCER", name = "Chronomancer", power = 0, carriers = {8, 5, 9, 2, 7, 11, 3}, coords = {0.125000, 0.250000, 0.000000, 0.250000}, specs = "Time, Infinite, Artificer" },
    { byte = 25, token = "CULTIST", name = "Cultist", power = 0, carriers = {8, 5, 9, 2, 7, 11, 3}, coords = {0.250000, 0.375000, 0.000000, 0.250000}, specs = "Heretic, Corruption, Godblade, Dreadnought" },
    { byte = 14, token = "DEMONHUNTER", name = "Felsworn", power = 3, carriers = {4}, coords = {0.500000, 0.625000, 0.000000, 0.250000}, specs = "Infernal, Slayer, Tyrant" },
    { byte = 18, token = "GUARDIAN", name = "Guardian", power = 3, carriers = {4}, coords = {0.875000, 1.000000, 0.000000, 0.250000}, specs = "Gladiator, Inspiration, Vanguard" },
    { byte = 17, token = "FLESHWARDEN", name = "Knight of Xoroth", power = 1, carriers = {1}, coords = {0.750000, 0.875000, 0.000000, 0.250000}, specs = "Hellfire, Defiance, War" },
    { byte = 23, token = "NECROMANCER", name = "Necromancer", power = 6, carriers = {6}, coords = {0.500000, 0.625000, 0.250000, 0.500000}, specs = "Death, Animation, Rime" },
    { byte = 31, token = "WILDWALKER", name = "Primalist", power = 0, carriers = {8, 5, 9, 2, 7, 11, 3}, coords = {0.625000, 0.750000, 0.750000, 1.000000}, specs = "Grovekeeper, Wildwalker, Mountain King, Geomancy" },
    { byte = 24, token = "PYROMANCER", name = "Pyromancer", power = 0, carriers = {8, 5, 9, 2, 7, 11, 3}, coords = {0.000000, 0.125000, 0.500000, 0.750000}, specs = "Flameweaving, Incineration, Draconic" },
    { byte = 21, token = "RANGER", name = "Ranger", power = 2, carriers = {3, 8, 5, 9, 2, 7, 11}, coords = {0.125000, 0.250000, 0.500000, 0.750000}, specs = "Archery, Farstrider, Brigand" },
    { byte = 30, token = "REAPER", name = "Reaper", power = 6, carriers = {6}, coords = {0.250000, 0.375000, 0.500000, 0.750000}, specs = "Soul, Harvest, Domination" },
    { byte = 32, token = "SPIRITMAGE", name = "Runemaster", power = 0, carriers = {8, 5, 9, 2, 7, 11, 3}, coords = {0.750000, 0.875000, 0.500000, 0.750000}, specs = "Engravement, Glyphic, Riftblade" },
    { byte = 26, token = "STARCALLER", name = "Starcaller", power = 3, carriers = {4}, coords = {0.875000, 1.000000, 0.500000, 0.750000}, specs = "Moon Priest, Sentinel, Warden, Moon Guard" },
    { byte = 16, token = "STORMBRINGER", name = "Stormbringer", power = 0, carriers = {8, 5, 9, 2, 7, 11, 3}, coords = {0.000000, 0.125000, 0.750000, 1.000000}, specs = "Wind, Maelstrom, Lightning" },
    { byte = 27, token = "SUNCLERIC", name = "Sun Cleric", power = 0, carriers = {8, 5, 9, 2, 7, 11, 3}, coords = {0.125000, 0.250000, 0.750000, 1.000000}, specs = "Piety, Valkyrie, Seraphim, Blessings" },
    { byte = 19, token = "MONK", name = "Templar", power = 3, carriers = {4}, coords = {0.375000, 0.500000, 0.250000, 0.500000}, specs = "Oathkeeper, Zealot, Crusader" },
    { byte = 28, token = "TINKER", name = "Tinker", power = 0, carriers = {8, 5, 9, 2, 7, 11, 3}, coords = {0.250000, 0.375000, 0.750000, 1.000000}, specs = "Demolition, Mechanics, Invention" },
    { byte = 29, token = "PROPHET", name = "Venomancer", power = 0, carriers = {8, 5, 9, 2, 7, 11, 3}, coords = {0.875000, 1.000000, 0.250000, 0.500000}, specs = "Fortitude, Stalking, Rot, Vizier" },
    { byte = 13, token = "WITCHDOCTOR", name = "Witch Doctor", power = 0, carriers = {8, 5, 9, 2, 7, 11, 3}, coords = {0.750000, 0.875000, 0.750000, 1.000000}, specs = "Shadowhunting, Voodoo, Brewing" },
    { byte = 15, token = "WITCHHUNTER", name = "Witch Hunter", power = 0, carriers = {8, 5, 9, 2, 7, 11, 3}, coords = {0.875000, 1.000000, 0.750000, 1.000000}, specs = "Boltslinger, Houndmaster, Inquisition, Black Knight" },
}
