-- AscensionCreate.lua: the Ascension class chooser on the STOCK character-create screen.
--
-- The stock screen offers the ten stock classes. This overlay hides those buttons and
-- shows ASC_CREATE_CLASSES (generated by tools/gen_glue_data.py) instead. Picking a class
-- selects, underneath, a stock "carrier" class with the same power bar (the only thing the
-- server can create), and the choice itself travels to the world through the one channel
-- glue Lua has: a registered string CVar nobody reads while voice chat is off. The addon
-- pack reads "ASC:<name>:<byte>:<archetype>" on the character's first world entry and
-- tells mod-ascension-ca (see core/Live.lua, verb CLASS).
ASC_CREATE_MAILBOX = "Sound_VoiceChatInputDriverName"
ASC_CREATE_PER_ROW = 8

local STOCK_TOKEN = { [1] = "WARRIOR", [2] = "PALADIN", [3] = "HUNTER", [4] = "ROGUE", [5] = "PRIEST",
                      [6] = "DEATHKNIGHT", [7] = "SHAMAN", [8] = "MAGE", [9] = "WARLOCK", [11] = "DRUID" }
local buttons = {}
local selected -- row of ASC_CREATE_CLASSES

-- One client serves both stock-client realms; the chooser belongs to the Conquest of Azeroth
-- one. ASC_CREATE_COA_REALMS (generated) names those realms; on any other realm (the Free-Pick
-- "Ascension" realm, where every character is a Hero) the stock create screen is untouched.
local function coaRealm()
    if ASC_CREATE_COA_REALMS == nil then return true end
    local name = GetServerName and GetServerName()
    return name ~= nil and ASC_CREATE_COA_REALMS[name] == true
end
AscensionCreate_IsCoARealm = coaRealm

-- index (1-based, into GetAvailableClasses() triples) of the first carrier the selected race can be
local function carrierIndex(row)
    local list = { GetAvailableClasses() }
    for _, stockClass in ipairs(row.carriers) do
        local token = STOCK_TOKEN[stockClass]
        for i = 1, #list, 3 do
            local index = (i + 2) / 3
            if token and strupper(list[i + 1]) == token and list[i + 2] == 1 and IsRaceClassValid(GetSelectedRace(), index) then
                return index
            end
        end
    end
end

-- The stock flow (SetCharacterClass) fills the class name, header, icon and description
-- for the carrier; this re-fills them for the chosen Ascension class and runs after it.
local function describe(row)
    if CharacterCreateClassName then CharacterCreateClassName:SetText(row.name) end
    if CharacterCreateClassLabel then CharacterCreateClassLabel:SetText(row.name) end
    if CharacterCreateClassIcon and row.coords then
        CharacterCreateClassIcon:SetTexture(ASC_CREATE_TEXTURE)
        CharacterCreateClassIcon:SetTexCoord(row.coords[1], row.coords[2], row.coords[3], row.coords[4])
    end
    if CharacterCreateClassText then
        local carrier = carrierIndex(row)
        local list = { GetAvailableClasses() }
        local carrierName = carrier and list[(carrier - 1) * 3 + 1] or "?"
        CharacterCreateClassText:SetText((row.specs ~= "" and ("- Specializations: " .. row.specs .. "\n\n") or "")
            .. "A Conquest of Azeroth class. Abilities and talents come from the Character Advancement panel in the world.\n\n"
            .. "|cff808080Created as a " .. carrierName .. " underneath (same power bar); the world server switches the identity on first login.|r")
    end
    return row.name
end

local function applyCarrier(row)
    local index = carrierIndex(row)
    if not index then return false end
    local _, _, current = GetSelectedClass()
    if current ~= index then
        SetSelectedClass(index)
        SetCharacterClass(index)
        SetCharacterRace(GetSelectedRace())
        CharacterChangeFixup()
    end
    return true
end

function AscensionCreate_Select(row)
    if not row then return end
    selected = row
    for _, b in ipairs(buttons) do b:SetChecked(b.row == row) end
    applyCarrier(row)
    describe(row)
end

function AscensionCreate_ClassButton_OnClick(self)
    PlaySound("gsCharacterCreationClass")
    if not self.enable then self:SetChecked(nil) return end
    AscensionCreate_Select(self.row)
end

function AscensionCreate_ClassButton_OnEnter(self)
    if CharacterCreateClassLabel and self.row then CharacterCreateClassLabel:SetText(strupper(self.row.name)) end
end

function AscensionCreate_ClassButton_OnLeave(self)
    if CharacterCreateClassLabel and selected then CharacterCreateClassLabel:SetText(strupper(selected.name)) end
end

-- Enabled state per race: a class needs at least one carrier the race can be.
function AscensionCreate_Refresh()
    if not ASC_CREATE_CLASSES then return end
    for _, b in ipairs(buttons) do
        b.enable = carrierIndex(b.row) ~= nil
        if b.enable then
            b:Enable()
            b:GetNormalTexture():SetDesaturated(nil)
            b.tooltip = b.row.name
        else
            b:Disable()
            b:GetNormalTexture():SetDesaturated(1)
            b.tooltip = b.row.name .. " (no carrier class for this race)"
        end
    end
    if not selected or not carrierIndex(selected) then
        for _, b in ipairs(buttons) do
            if b.enable then AscensionCreate_Select(b.row) break end
        end
    else
        AscensionCreate_Select(selected)
    end
end

function AscensionCreate_OnLoad(self)
    if not ASC_CREATE_CLASSES or not CharacterCreateClassButton1 then return end
    -- the stock row holds ten 40px buttons in two rows of five; 21 classes fit the same
    -- box as three rows of eight 28px buttons
    local anchor = CharacterCreateClassButton1
    local w, h, gap = 28, 28, 3
    for i, row in ipairs(ASC_CREATE_CLASSES) do
        local b = CreateFrame("CheckButton", "AscensionCreateClassButton" .. i, self, "AscensionCreateClassButtonTemplate")
        b.row = row
        b:SetWidth(w)
        b:SetHeight(h)
        local col, line = (i - 1) % ASC_CREATE_PER_ROW, math.floor((i - 1) / ASC_CREATE_PER_ROW)
        b:SetPoint("TOPLEFT", anchor, "TOPLEFT", col * (w + gap), -line * (h + gap))
        local c = row.coords
        b:GetNormalTexture():SetTexture(ASC_CREATE_TEXTURE)
        b:GetNormalTexture():SetTexCoord(c[1], c[2], c[3], c[4])
        b:GetPushedTexture():SetTexture(ASC_CREATE_TEXTURE)
        b:GetPushedTexture():SetTexCoord(c[1], c[2], c[3], c[4])
        buttons[#buttons + 1] = b
    end
end

-- Hooks into the stock flow. CharacterCreateEnumerateClasses runs on show and on every
-- race click; we hide the stock buttons after it and refresh ours.
local stockEnumerate = CharacterCreateEnumerateClasses
function CharacterCreateEnumerateClasses(...)
    stockEnumerate(...)
    if not ASC_CREATE_CLASSES then return end
    if not coaRealm() then
        for _, b in ipairs(buttons) do b:Hide() end
        selected = nil
        return
    end
    for _, b in ipairs(buttons) do b:Show() end
    for i = 1, (MAX_CLASSES_PER_RACE or 10) do
        local b = _G["CharacterCreateClassButton" .. i]
        if b then b:Hide() end
    end
    AscensionCreate_Refresh()
end

-- CharacterCreate_OnShow calls SetCharacterClass(carrier) AFTER enumerating classes, which
-- refills the name/icon/description with the carrier's; put the Ascension class back.
local stockSetClass = SetCharacterClass
function SetCharacterClass(id)
    stockSetClass(id)
    if selected and ASC_CREATE_CLASSES and coaRealm() then describe(selected) end
end

-- Character select is keyboard-navigable in the stock client except for one button: Create
-- New Character has no key. INSERT opens it (the stock create screen focuses the name box, so
-- a name and ENTER finish the job), which is also what lets a screen reader or a test harness
-- create a character without a mouse.
local stockSelectKey = CharacterSelect_OnKeyDown
if stockSelectKey then
    function CharacterSelect_OnKeyDown(self, key, ...)
        if (key == "INSERT" or key == "F5") and SetGlueScreen then
            PlaySound("gsCharacterSelectionCreateNew")
            SetGlueScreen("charcreate") -- what CharSelectCreateCharacterButton's OnClick does (CharacterSelect.lua:534)
            return
        end
        return stockSelectKey(self, key, ...)
    end
end

local stockOkay = CharacterCreate_Okay
function CharacterCreate_Okay()
    if selected and ASC_CREATE_CLASSES and coaRealm() then
        local name = CharacterCreateNameEdit:GetText() or ""
        pcall(SetCVar, ASC_CREATE_MAILBOX, "ASC:" .. name .. ":" .. selected.byte .. ":")
    end
    stockOkay()
end
