#!/usr/bin/env python3
"""Generate the mod-ascension-ca server tables from one generated dataset.

    python gen_server_sql.py --dataset data/datasets/unattributed-7f0c805382 --out server/sql

Reads the dataset's entries.json and tables.json (both produced by gen_ca_data.py, so a fact
still exists once) and writes

    <out>/world/ascension_ca_world.sql          reference data, idempotent (CREATE IF NOT EXISTS + REPLACE)
    <out>/characters/ascension_ca_characters.sql   per-character state, schema only

The module (server/mod-ascension-ca) loads the world tables at startup and never parses
JSON: every rule it enforces is an explicit column here.  Costs follow the CoA model the
UI displays (one point per rank; the "Class" tab spends AE, specialization tabs spend
TE) -- the harvested AECost/TECost columns are carried along for the classic mode later.
"""
import argparse, json, os, sys, time


def q(s):
    if s is None:
        return "NULL"
    return "'" + str(s).replace("\\", "\\\\").replace("'", "''") + "'"


def n(v, default=0):
    if v is None or v == "":
        return default
    try:
        return int(v)
    except (TypeError, ValueError):
        return default


def main():
    ap = argparse.ArgumentParser(description=__doc__)
    ap.add_argument("--dataset", required=True, help="data/datasets/<key>")
    ap.add_argument("--out", required=True, help="output root (world/ and characters/ are created)")
    ap.add_argument("--chrclasses", help="Ascension's 32-row ChrClasses.dbc (power type -> carrier class)")
    ap.add_argument("--builds", help="builds.json: 56 archetype builds keyed by UUID {name, roles, entries}")
    a = ap.parse_args()
    key = os.path.basename(os.path.normpath(a.dataset))
    entries = json.load(open(os.path.join(a.dataset, "entries.json"), encoding="utf-8-sig"))
    tables = json.load(open(os.path.join(a.dataset, "tables.json"), encoding="utf-8-sig"))
    ids = {e["ID"] for e in entries}
    entry_class = {e["ID"]: e.get("ClassTypeID", 0) for e in entries}

    # power type per class byte (ChrClasses field 2): the carrier is the stock class with the
    # same power bar, which is what the client renders from the class byte it was created with.
    CARRIER = {0: 8, 1: 1, 2: 3, 3: 4, 6: 6}  # mana->Mage, rage->Warrior, focus->Hunter, energy->Rogue, runic->Death Knight
    power = {}
    if a.chrclasses:
        import struct
        raw = open(a.chrclasses, "rb").read()
        _, nrec, nfld, rsize, _ = struct.unpack_from("<4sIIII", raw, 0)
        for r in range(nrec):
            row = struct.unpack_from("<%di" % nfld, raw, 20 + r * rsize)
            power[row[0]] = row[2]
    builds = json.load(open(a.builds, encoding="utf-8-sig")) if a.builds else {}

    w = []
    w.append("-- generated by gen_server_sql.py from dataset %s on %s; do not edit\n" % (key, time.strftime("%Y-%m-%d")))
    # reference data is regenerated whole: drop, so a vanished row cannot linger
    for t in ("ascension_ca_dataset", "ascension_ca_class", "ascension_ca_spec", "ascension_ca_entry",
              "ascension_ca_entry_spell", "ascension_ca_entry_link", "ascension_ca_essence",
              "ascension_ca_archetype", "ascension_ca_archetype_entry"):
        w.append("DROP TABLE IF EXISTS %s;" % t)
    w.append("CREATE TABLE IF NOT EXISTS ascension_ca_dataset (dataset VARCHAR(64) NOT NULL PRIMARY KEY, generated_at VARCHAR(32) NOT NULL) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;")
    w.append("CREATE TABLE IF NOT EXISTS ascension_ca_class (class_byte TINYINT UNSIGNED NOT NULL PRIMARY KEY, token VARCHAR(32) NOT NULL, name VARCHAR(64) NOT NULL, ca_class_type INT UNSIGNED NOT NULL, ca_class_name VARCHAR(64) NOT NULL, power_type TINYINT UNSIGNED NOT NULL DEFAULT 0, carrier_class TINYINT UNSIGNED NOT NULL DEFAULT 0) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;")
    w.append("CREATE TABLE IF NOT EXISTS ascension_ca_archetype (uuid CHAR(36) NOT NULL PRIMARY KEY, name VARCHAR(64) NOT NULL, class_type INT UNSIGNED NOT NULL, roles VARCHAR(64) NOT NULL, num_entries INT UNSIGNED NOT NULL) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;")
    w.append("CREATE TABLE IF NOT EXISTS ascension_ca_archetype_entry (uuid CHAR(36) NOT NULL, ordinal INT UNSIGNED NOT NULL, entry INT UNSIGNED NOT NULL, `rank` TINYINT UNSIGNED NOT NULL, PRIMARY KEY(uuid, ordinal)) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;")
    w.append("CREATE TABLE IF NOT EXISTS ascension_ca_spec (id INT UNSIGNED NOT NULL PRIMARY KEY, class_token VARCHAR(32) NOT NULL, spec_token VARCHAR(32) NOT NULL, name VARCHAR(64) NOT NULL, passive_spell INT UNSIGNED NOT NULL DEFAULT 0) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;")
    w.append("CREATE TABLE IF NOT EXISTS ascension_ca_entry (entry INT UNSIGNED NOT NULL PRIMARY KEY, class_type INT UNSIGNED NOT NULL, class_name VARCHAR(64) NOT NULL, tab_type INT UNSIGNED NOT NULL, tab_name VARCHAR(64) NOT NULL, is_class_tab TINYINT UNSIGNED NOT NULL, entry_type VARCHAR(16) NOT NULL, name VARCHAR(128) NOT NULL, max_rank TINYINT UNSIGNED NOT NULL, ae_cost INT UNSIGNED NOT NULL, te_cost INT UNSIGNED NOT NULL, req_level INT UNSIGNED NOT NULL, req_tab_ae INT UNSIGNED NOT NULL, req_tab_te INT UNSIGNED NOT NULL, req_class_ae INT UNSIGNED NOT NULL, req_class_te INT UNSIGNED NOT NULL, req_ae INT UNSIGNED NOT NULL, req_te INT UNSIGNED NOT NULL, req_class_points INT UNSIGNED NOT NULL, row_index INT NOT NULL, col_index INT NOT NULL, node_type VARCHAR(32) NOT NULL, flags INT UNSIGNED NOT NULL, KEY(class_type)) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;")
    w.append("CREATE TABLE IF NOT EXISTS ascension_ca_entry_spell (entry INT UNSIGNED NOT NULL, rank_index TINYINT UNSIGNED NOT NULL, spell INT UNSIGNED NOT NULL, PRIMARY KEY(entry, rank_index)) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;")
    w.append("CREATE TABLE IF NOT EXISTS ascension_ca_entry_link (entry INT UNSIGNED NOT NULL, kind VARCHAR(8) NOT NULL, target INT UNSIGNED NOT NULL, resolved TINYINT UNSIGNED NOT NULL, PRIMARY KEY(entry, kind, target)) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;")
    w.append("CREATE TABLE IF NOT EXISTS ascension_ca_essence (family TINYINT UNSIGNED NOT NULL, level TINYINT UNSIGNED NOT NULL, ae INT UNSIGNED NOT NULL, te INT UNSIGNED NOT NULL, PRIMARY KEY(family, level)) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;")
    w.append("REPLACE INTO ascension_ca_dataset VALUES (%s, %s);" % (q(key), q(time.strftime("%Y-%m-%dT%H:%M:%S"))))

    type_of_byte = {}
    for c in tables["classIdentities"]:
        if "CAClassTypeID" not in c:
            continue
        byte = n(c["ID"])
        pw = power.get(byte, 0)
        carrier = byte if byte <= 11 else CARRIER.get(pw, 8)
        type_of_byte[byte] = n(c["CAClassTypeID"])
        w.append("REPLACE INTO ascension_ca_class VALUES (%d, %s, %s, %d, %s, %d, %d);" % (
            byte, q(c["Token"]), q(c["Name"]), n(c["CAClassTypeID"]), q(c.get("CAClassName", c["Name"])), pw, carrier))
    for s in tables["specs"]:
        w.append("REPLACE INTO ascension_ca_spec VALUES (%d, %s, %s, %s, %d);" % (
            n(s["ID"]), q(s["Class"]), q(s["Spec"]), q(s.get("Name", s["Spec"])), n(s.get("PassiveSpell"))))
    # archetypes: the class is the class of the build's entries (every recovered build is single-class)
    for uuid, b in sorted(builds.items()):
        ents = b.get("entries") or []
        classes = {entry_class.get(n(x.get("id")), 0) for x in ents} - {0}
        ctype = next(iter(classes)) if len(classes) == 1 else 0
        roles = b.get("roles")
        roles = ",".join(roles) if isinstance(roles, list) else str(roles or "")
        w.append("REPLACE INTO ascension_ca_archetype VALUES (%s, %s, %d, %s, %d);" % (q(uuid), q(b.get("name", "")), ctype, q(roles), len(ents)))
        for i, x in enumerate(ents):
            w.append("REPLACE INTO ascension_ca_archetype_entry VALUES (%s, %d, %d, %d);" % (q(uuid), i + 1, n(x.get("id")), max(1, n(x.get("rank"), 1))))

    # essence: one (family, level) row; when the harvest carries variants, the all-zero Match
    # row is the plain one.
    ess = {}
    for r in tables["essence"]:
        k = (n(r["Family"]), n(r["Level"]))
        plain = not any(n(r.get("Match%d" % i)) for i in (1, 2, 3, 4))
        if k not in ess or (plain and not ess[k][2]):
            ess[k] = (n(r["AE"]), n(r["TE"]), plain)
    for (fam, lvl), (ae, te, _) in sorted(ess.items()):
        w.append("REPLACE INTO ascension_ca_essence VALUES (%d, %d, %d, %d);" % (fam, lvl, ae, te))

    unresolved = 0
    for e in sorted(entries, key=lambda x: x["ID"]):
        spells = e.get("Spells") or e.get("SpellIDs") or []
        max_rank = max(1, len(spells))
        w.append("REPLACE INTO ascension_ca_entry VALUES (%d, %d, %s, %d, %s, %d, %s, %s, %d, %d, %d, %d, %d, %d, %d, %d, %d, %d, %d, %d, %d, %s, %d);" % (
            n(e["ID"]), n(e.get("ClassTypeID")), q(e.get("Class", "")), n(e.get("TabTypeID")), q(e.get("Tab", "")),
            1 if e.get("Tab") == "Class" else 0, q(e.get("Type", "")), q(e.get("Name", "")), max_rank,
            n(e.get("AECost")), n(e.get("TECost")), n(e.get("RequiredLevel")),
            n(e.get("RequiredTabAEInvestment")), n(e.get("RequiredTabTEInvestment")),
            n(e.get("RequiredClassAEInvestment")), n(e.get("RequiredClassTEInvestment")),
            n(e.get("RequiredAEInvestment")), n(e.get("RequiredTEInvestment")), n(e.get("RequiredClassPoints")),
            n(e.get("Row")), n(e.get("Column")), q(e.get("NodeType", "")), n(e.get("Flags"))))
        for i, sp in enumerate(spells):
            w.append("REPLACE INTO ascension_ca_entry_spell VALUES (%d, %d, %d);" % (n(e["ID"]), i + 1, n(sp)))
        for kind, key_name in (("req", "RequiredIDs"), ("conn", "ConnectedNodes"), ("mastery", "Masteries")):
            for t in e.get(key_name) or []:
                resolved = 1 if n(t) in ids else 0
                unresolved += 0 if resolved else 1
                w.append("REPLACE INTO ascension_ca_entry_link VALUES (%d, %s, %d, %d);" % (n(e["ID"]), q(kind), n(t), resolved))

    os.makedirs(os.path.join(a.out, "world"), exist_ok=True)
    os.makedirs(os.path.join(a.out, "characters"), exist_ok=True)
    with open(os.path.join(a.out, "world", "ascension_ca_world.sql"), "w", encoding="utf-8", newline="\n") as f:
        f.write("\n".join(w) + "\n")
    chars = [
        "-- mod-ascension-ca per-character state (characters database)",
        "CREATE TABLE IF NOT EXISTS ascension_ca_character (guid INT UNSIGNED NOT NULL PRIMARY KEY, class_byte TINYINT UNSIGNED NOT NULL, spec_id INT UNSIGNED NOT NULL DEFAULT 0, chosen TINYINT UNSIGNED NOT NULL DEFAULT 0, archetype CHAR(36) NOT NULL DEFAULT '', updated_at INT UNSIGNED NOT NULL DEFAULT 0) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;",
        "CREATE TABLE IF NOT EXISTS ascension_ca_known (guid INT UNSIGNED NOT NULL, entry INT UNSIGNED NOT NULL, `rank` TINYINT UNSIGNED NOT NULL, PRIMARY KEY(guid, entry)) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;",
    ]
    with open(os.path.join(a.out, "characters", "ascension_ca_characters.sql"), "w", encoding="utf-8", newline="\n") as f:
        f.write("\n".join(chars) + "\n")
    print("dataset %s: %d entries, %d classes (%d with a power type), %d specs, %d essence rows, %d archetypes, %d unresolved link targets -> %s" % (
        key, len(entries), len(type_of_byte), len(power), len(tables["specs"]), len(ess), len(builds), unresolved, a.out))
    return 0


if __name__ == "__main__":
    sys.exit(main())
