#!/usr/bin/env python3
"""Generate the glue-side class chooser data (Interface\\GlueXML\\AscensionCreateData.lua).

    python gen_glue_data.py --dataset data/datasets/<key> --chrclasses <Ascension ChrClasses.dbc>
                            --atlas <ui-tree>\\Interface\\SharedXML\\AtlasInfo.lua --out <file.lua>
                            [--mode coa]

The stock character-create screen cannot show Ascension's classes; the overlay in
client/Interface/GlueXML draws them from this table:

    ASC_CREATE_TEXTURE = "Interface\\Glues\\CHARACTERCREATE\\UI-CHARACTERCREATE-CLASSES"
    ASC_CREATE_CLASSES = { { byte, token, name, power, carriers = {stock class ids...},
                             coords = {l, r, t, b}, specs = "Demolition, Mechanics, Invention" }, ... }

Icons are Ascension's own "class-<token>" atlas entries (their patch-A version of the stock
class sheet holds every class). Carriers are the stock classes whose power bar matches the
class's ChrClasses power type, in preference order; the overlay picks the first one the
selected race can be. Mode coa lists the 21 CoA classes; hero lists the stock ten + HERO.
"""
import argparse, json, re, struct, sys

# stock class id -> power the 3.3.5 client draws for it (hunters run on mana here)
STOCK_POWER = {1: 1, 4: 3, 6: 6}
CARRIERS_BY_POWER = {
    0: [8, 5, 9, 2, 7, 11, 3],   # mana: mage, priest, warlock, paladin, shaman, druid, hunter
    2: [3, 8, 5, 9, 2, 7, 11],   # focus (Ranger): hunter first, then the mana carriers
    1: [1],                      # rage
    3: [4],                      # energy
    6: [6],                      # runic power
}


def lua_str(s):
    return '"' + str(s).replace("\\", "\\\\").replace('"', '\\"') + '"'


def main():
    ap = argparse.ArgumentParser(description=__doc__)
    ap.add_argument("--dataset", required=True)
    ap.add_argument("--chrclasses", required=True)
    ap.add_argument("--atlas", required=True)
    ap.add_argument("--out", required=True)
    ap.add_argument("--mode", default="coa", choices=["coa", "hero"])
    a = ap.parse_args()
    tables = json.load(open(a.dataset.rstrip("\\/") + "/tables.json", encoding="utf-8-sig"))
    raw = open(a.chrclasses, "rb").read()
    _, nrec, nfld, rsize, _ = struct.unpack_from("<4sIIII", raw, 0)
    power = {}
    for r in range(nrec):
        row = struct.unpack_from("<%di" % nfld, raw, 20 + r * rsize)
        power[row[0]] = row[2]
    atlas_text = open(a.atlas, encoding="utf-8", errors="replace").read()
    atlas = {}
    texture = None
    for m in re.finditer(r'\["class-([a-z]+)"\]\s*=\s*\{\s*"([^"]+)"\s*,\s*[\d.]+\s*,\s*[\d.]+\s*,\s*([\d.]+)\s*,\s*([\d.]+)\s*,\s*([\d.]+)\s*,\s*([\d.]+)', atlas_text):
        atlas[m.group(1).upper()] = tuple(float(x) for x in m.group(3, 4, 5, 6))
        texture = texture or m.group(2).replace("\\\\", "\\")
    specs_by_class = {}
    for s in tables["specs"]:
        specs_by_class.setdefault(s["Class"], []).append(s.get("Name", s["Spec"]))
    rows = []
    for c in tables["classIdentities"]:
        byte, token = int(c["ID"]), c["Token"]
        coa = byte >= 12 and token != "HERO"
        if (a.mode == "coa") != coa:
            continue
        pw = power.get(byte, 0)
        carriers = [byte] if byte <= 11 else CARRIERS_BY_POWER.get(pw, CARRIERS_BY_POWER[0])
        coords = atlas.get(token)
        if not coords:
            print("!! no class-%s atlas entry; class skipped" % token.lower())
            continue
        rows.append((c["Name"], byte, token, pw, carriers, coords, ", ".join(specs_by_class.get(token, []))))
    rows.sort()
    with open(a.out, "w", encoding="utf-8", newline="\n") as f:
        f.write("-- generated by tools/gen_glue_data.py (mode %s); do not edit\n" % a.mode)
        f.write("ASC_CREATE_MODE = %s\n" % lua_str(a.mode))
        f.write("ASC_CREATE_TEXTURE = %s\n" % lua_str(texture or "Interface\\Glues\\CHARACTERCREATE\\UI-CHARACTERCREATE-CLASSES"))
        f.write("ASC_CREATE_CLASSES = {\n")
        for name, byte, token, pw, carriers, coords, specs in rows:
            f.write("    { byte = %d, token = %s, name = %s, power = %d, carriers = {%s}, coords = {%s}, specs = %s },\n" % (
                byte, lua_str(token), lua_str(name), pw, ", ".join(str(x) for x in carriers),
                ", ".join("%.6f" % x for x in coords), lua_str(specs)))
        f.write("}\n")
    print("%s: %d classes -> %s" % (a.mode, len(rows), a.out))
    return 0


if __name__ == "__main__":
    sys.exit(main())
