#!/usr/bin/env python3
"""Generate the mod-ascension-ca server tables from one generated dataset.

    python gen_server_sql.py --dataset data/datasets/unattributed-7f0c805382 --out server/sql

Reads the dataset's entries.json and tables.json (both produced by gen_ca_data.py, so a fact
still exists once) and writes

    <out>/world/ascension_ca_world.sql          reference data, idempotent (CREATE IF NOT EXISTS + REPLACE)
    <out>/characters/ascension_ca_characters.sql   per-character state, schema only

The module (server/mod-ascension-ca) loads the world tables at startup and never parses
JSON: every rule it enforces is an explicit column here.  Costs follow the CoA model the
UI displays (one point per rank; the "Class" tab spends AE, specialization tabs spend
TE) -- the harvested AECost/TECost columns are carried along for the classic mode later.
"""
import argparse, json, os, sys, time


def q(s):
    if s is None:
        return "NULL"
    return "'" + str(s).replace("\\", "\\\\").replace("'", "''") + "'"


def n(v, default=0):
    if v is None or v == "":
        return default
    try:
        return int(v)
    except (TypeError, ValueError):
        return default


def main():
    ap = argparse.ArgumentParser(description=__doc__)
    ap.add_argument("--dataset", required=True, help="data/datasets/<key>")
    ap.add_argument("--out", required=True, help="output root (world/ and characters/ are created)")
    a = ap.parse_args()
    key = os.path.basename(os.path.normpath(a.dataset))
    entries = json.load(open(os.path.join(a.dataset, "entries.json"), encoding="utf-8-sig"))
    tables = json.load(open(os.path.join(a.dataset, "tables.json"), encoding="utf-8-sig"))
    ids = {e["ID"] for e in entries}

    w = []
    w.append("-- generated by gen_server_sql.py from dataset %s on %s; do not edit\n" % (key, time.strftime("%Y-%m-%d")))
    w.append("CREATE TABLE IF NOT EXISTS ascension_ca_dataset (dataset VARCHAR(64) NOT NULL PRIMARY KEY, generated_at VARCHAR(32) NOT NULL) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;")
    w.append("CREATE TABLE IF NOT EXISTS ascension_ca_class (class_byte TINYINT UNSIGNED NOT NULL PRIMARY KEY, token VARCHAR(32) NOT NULL, name VARCHAR(64) NOT NULL, ca_class_type INT UNSIGNED NOT NULL, ca_class_name VARCHAR(64) NOT NULL) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;")
    w.append("CREATE TABLE IF NOT EXISTS ascension_ca_spec (id INT UNSIGNED NOT NULL PRIMARY KEY, class_token VARCHAR(32) NOT NULL, spec_token VARCHAR(32) NOT NULL, name VARCHAR(64) NOT NULL, passive_spell INT UNSIGNED NOT NULL DEFAULT 0) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;")
    w.append("CREATE TABLE IF NOT EXISTS ascension_ca_entry (entry INT UNSIGNED NOT NULL PRIMARY KEY, class_type INT UNSIGNED NOT NULL, class_name VARCHAR(64) NOT NULL, tab_type INT UNSIGNED NOT NULL, tab_name VARCHAR(64) NOT NULL, is_class_tab TINYINT UNSIGNED NOT NULL, entry_type VARCHAR(16) NOT NULL, name VARCHAR(128) NOT NULL, max_rank TINYINT UNSIGNED NOT NULL, ae_cost INT UNSIGNED NOT NULL, te_cost INT UNSIGNED NOT NULL, req_level INT UNSIGNED NOT NULL, req_tab_ae INT UNSIGNED NOT NULL, req_tab_te INT UNSIGNED NOT NULL, req_class_ae INT UNSIGNED NOT NULL, req_class_te INT UNSIGNED NOT NULL, req_ae INT UNSIGNED NOT NULL, req_te INT UNSIGNED NOT NULL, req_class_points INT UNSIGNED NOT NULL, row_index INT NOT NULL, col_index INT NOT NULL, node_type VARCHAR(32) NOT NULL, flags INT UNSIGNED NOT NULL, KEY(class_type)) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;")
    w.append("CREATE TABLE IF NOT EXISTS ascension_ca_entry_spell (entry INT UNSIGNED NOT NULL, rank_index TINYINT UNSIGNED NOT NULL, spell INT UNSIGNED NOT NULL, PRIMARY KEY(entry, rank_index)) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;")
    w.append("CREATE TABLE IF NOT EXISTS ascension_ca_entry_link (entry INT UNSIGNED NOT NULL, kind VARCHAR(8) NOT NULL, target INT UNSIGNED NOT NULL, resolved TINYINT UNSIGNED NOT NULL, PRIMARY KEY(entry, kind, target)) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;")
    w.append("CREATE TABLE IF NOT EXISTS ascension_ca_essence (family TINYINT UNSIGNED NOT NULL, level TINYINT UNSIGNED NOT NULL, ae INT UNSIGNED NOT NULL, te INT UNSIGNED NOT NULL, PRIMARY KEY(family, level)) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;")
    w.append("REPLACE INTO ascension_ca_dataset VALUES (%s, %s);" % (q(key), q(time.strftime("%Y-%m-%dT%H:%M:%S"))))

    for c in tables["classIdentities"]:
        if "CAClassTypeID" not in c:
            continue
        w.append("REPLACE INTO ascension_ca_class VALUES (%d, %s, %s, %d, %s);" % (
            n(c["ID"]), q(c["Token"]), q(c["Name"]), n(c["CAClassTypeID"]), q(c.get("CAClassName", c["Name"]))))
    for s in tables["specs"]:
        w.append("REPLACE INTO ascension_ca_spec VALUES (%d, %s, %s, %s, %d);" % (
            n(s["ID"]), q(s["Class"]), q(s["Spec"]), q(s.get("Name", s["Spec"])), n(s.get("PassiveSpell"))))

    # essence: one (family, level) row; when the harvest carries variants, the all-zero Match
    # row is the plain one.
    ess = {}
    for r in tables["essence"]:
        k = (n(r["Family"]), n(r["Level"]))
        plain = not any(n(r.get("Match%d" % i)) for i in (1, 2, 3, 4))
        if k not in ess or (plain and not ess[k][2]):
            ess[k] = (n(r["AE"]), n(r["TE"]), plain)
    for (fam, lvl), (ae, te, _) in sorted(ess.items()):
        w.append("REPLACE INTO ascension_ca_essence VALUES (%d, %d, %d, %d);" % (fam, lvl, ae, te))

    unresolved = 0
    for e in sorted(entries, key=lambda x: x["ID"]):
        spells = e.get("Spells") or e.get("SpellIDs") or []
        max_rank = max(1, len(spells))
        w.append("REPLACE INTO ascension_ca_entry VALUES (%d, %d, %s, %d, %s, %d, %s, %s, %d, %d, %d, %d, %d, %d, %d, %d, %d, %d, %d, %d, %d, %s, %d);" % (
            n(e["ID"]), n(e.get("ClassTypeID")), q(e.get("Class", "")), n(e.get("TabTypeID")), q(e.get("Tab", "")),
            1 if e.get("Tab") == "Class" else 0, q(e.get("Type", "")), q(e.get("Name", "")), max_rank,
            n(e.get("AECost")), n(e.get("TECost")), n(e.get("RequiredLevel")),
            n(e.get("RequiredTabAEInvestment")), n(e.get("RequiredTabTEInvestment")),
            n(e.get("RequiredClassAEInvestment")), n(e.get("RequiredClassTEInvestment")),
            n(e.get("RequiredAEInvestment")), n(e.get("RequiredTEInvestment")), n(e.get("RequiredClassPoints")),
            n(e.get("Row")), n(e.get("Column")), q(e.get("NodeType", "")), n(e.get("Flags"))))
        for i, sp in enumerate(spells):
            w.append("REPLACE INTO ascension_ca_entry_spell VALUES (%d, %d, %d);" % (n(e["ID"]), i + 1, n(sp)))
        for kind, key_name in (("req", "RequiredIDs"), ("conn", "ConnectedNodes"), ("mastery", "Masteries")):
            for t in e.get(key_name) or []:
                resolved = 1 if n(t) in ids else 0
                unresolved += 0 if resolved else 1
                w.append("REPLACE INTO ascension_ca_entry_link VALUES (%d, %s, %d, %d);" % (n(e["ID"]), q(kind), n(t), resolved))

    os.makedirs(os.path.join(a.out, "world"), exist_ok=True)
    os.makedirs(os.path.join(a.out, "characters"), exist_ok=True)
    with open(os.path.join(a.out, "world", "ascension_ca_world.sql"), "w", encoding="utf-8", newline="\n") as f:
        f.write("\n".join(w) + "\n")
    chars = [
        "-- mod-ascension-ca per-character state (characters database)",
        "CREATE TABLE IF NOT EXISTS ascension_ca_character (guid INT UNSIGNED NOT NULL PRIMARY KEY, class_byte TINYINT UNSIGNED NOT NULL, spec_id INT UNSIGNED NOT NULL DEFAULT 0, updated_at INT UNSIGNED NOT NULL DEFAULT 0) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;",
        "CREATE TABLE IF NOT EXISTS ascension_ca_known (guid INT UNSIGNED NOT NULL, entry INT UNSIGNED NOT NULL, `rank` TINYINT UNSIGNED NOT NULL, PRIMARY KEY(guid, entry)) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;",
    ]
    with open(os.path.join(a.out, "characters", "ascension_ca_characters.sql"), "w", encoding="utf-8", newline="\n") as f:
        f.write("\n".join(chars) + "\n")
    print("dataset %s: %d entries, %d classes, %d specs, %d essence rows, %d unresolved link targets -> %s" % (
        key, len(entries), sum(1 for c in tables["classIdentities"] if "CAClassTypeID" in c), len(tables["specs"]), len(ess), unresolved, a.out))
    return 0


if __name__ == "__main__":
    sys.exit(main())
