"""Tests for the Conquest of Azeroth advancement catalogue reader.

Fixtures are written out rather than read from a server tree: the catalogue is
the realm's data and is not bundled, so the suite must not need a realm.
"""

import os
import sys
import tempfile
import unittest

sys.path.insert(0, os.path.dirname(os.path.abspath(__file__)))

import bms_coa  # noqa: E402
from bms_coa import Catalogue, CoaError, parse_header, parse_json  # noqa: E402


# Real rows, in the header's own layout:
# {EntryId, ClassId, SpecId, SpellCount, AECost, TECost, RequiredLevel, {{spells}}}
HEADER = """
// Generated by Tools/Generate-LocalCoATalentData.ps1.
#ifndef ASCENSION_COA_TALENT_DATA_H
namespace AscensionCompatData
{
struct CoATalentEntry { std::uint32_t EntryId; };
constexpr CoATalentEntry CoATalentEntries[] = {
    {4043, 26, 100, 1, 0, 0, 10, {{92132, 0, 0}}},
    {6313, 26, 0, 1, 1, 0, 0, {{300258, 0, 0}}},
    {6770, 26, 100, 1, 0, 1, 0, {{300250, 0, 0}}},
    {4044, 26, 44, 2, 0, 0, 10, {{300100, 300101, 0}}},
    {1001, 12, 1, 1, 0, 1, 20, {{500001, 0, 0}}},
};
}
#endif
"""


class HeaderTests(unittest.TestCase):
    def setUp(self):
        self.entries = parse_header(HEADER)

    def test_every_row_is_read(self):
        self.assertEqual([e.entry_id for e in self.entries],
                         [4043, 6313, 6770, 4044, 1001])

    def test_columns_land_in_the_right_fields(self):
        entry = {e.entry_id: e for e in self.entries}[6770]
        self.assertEqual(entry.class_id, 26)
        self.assertEqual(entry.spec_id, 100)
        self.assertEqual(entry.ability_cost, 0)
        self.assertEqual(entry.talent_cost, 1)
        self.assertEqual(entry.required_level, 0)
        self.assertEqual(entry.spells, (300250,))

    def test_trailing_zero_spells_are_dropped_but_real_ones_kept(self):
        entry = {e.entry_id: e for e in self.entries}[4044]
        self.assertEqual(entry.spells, (300100, 300101))

    def test_cost_decides_what_an_entry_is(self):
        by_id = {e.entry_id: e for e in self.entries}
        self.assertEqual(by_id[6770].kind, "talent")
        self.assertEqual(by_id[6313].kind, "ability")
        self.assertEqual(by_id[4043].kind, "automatic")

    def test_prose_around_the_table_is_not_mistaken_for_rows(self):
        self.assertEqual(len(parse_header("// {1, 2} nothing here\nint x[] = {1, 2, 3};")), 0)


class JsonTests(unittest.TestCase):
    def test_the_cpp_spelling_is_accepted(self):
        entries = parse_json('[{"EntryId": 7, "ClassId": 26, "SpecId": 100, '
                             '"AECost": 0, "TECost": 1, "RequiredLevel": 5, '
                             '"SpellIds": [11, 12]}]')
        self.assertEqual(entries[0].entry_id, 7)
        self.assertEqual(entries[0].spells, (11, 12))
        self.assertEqual(entries[0].required_level, 5)

    def test_a_lowercase_hand_written_export_is_accepted(self):
        entries = parse_json('{"entries": [{"entry": 9, "class": 12, "spell": 5}]}')
        self.assertEqual(entries[0].entry_id, 9)
        self.assertEqual(entries[0].class_id, 12)
        self.assertEqual(entries[0].spells, (5,))

    def test_the_captured_field_name_also_works(self):
        """A checkpoint calls the same id InternalID."""
        entries = parse_json('[{"InternalID": 4043, "ClassId": 26, "SpellID": 92132}]')
        self.assertEqual(entries[0].entry_id, 4043)
        self.assertEqual(entries[0].spells, (92132,))

    def test_malformed_json_says_so(self):
        with self.assertRaises(CoaError):
            parse_json("{not json")

    def test_json_that_is_not_a_list_of_entries_says_so(self):
        with self.assertRaises(CoaError):
            parse_json('{"something": 1}')


class CatalogueTests(unittest.TestCase):
    def setUp(self):
        self.cat = Catalogue(entries=parse_header(HEADER))

    def test_entries_are_reachable_by_the_id_a_checkpoint_records(self):
        self.assertEqual(self.cat.get(4043).spells, (92132,))
        self.assertEqual(self.cat.get("4043").spells, (92132,))
        self.assertIsNone(self.cat.get(None))
        self.assertIsNone(self.cat.get("nonsense"))

    def test_classes_and_specs_are_reported(self):
        self.assertEqual(self.cat.classes(), [12, 26])
        self.assertEqual(self.cat.specs(26), [44, 100])

    def test_a_duplicate_id_is_counted_rather_than_silently_preferred(self):
        doubled = Catalogue(entries=parse_header(HEADER) + parse_header(HEADER))
        self.assertEqual(len(doubled), 5)
        self.assertEqual(doubled.duplicates, 5)

    def test_an_entry_of_another_class_is_a_mismatch(self):
        self.assertIn("class 26", self.cat.mismatch(4043, 12, 80))

    def test_an_entry_above_the_characters_level_is_a_mismatch(self):
        self.assertIn("needs level 10", self.cat.mismatch(4043, 26, 5))

    def test_an_entry_of_another_specialization_is_a_mismatch(self):
        self.assertIn("specialization", self.cat.mismatch(4043, 26, 80, 44))

    def test_a_specless_entry_suits_any_specialization(self):
        self.assertEqual(self.cat.mismatch(6313, 26, 80, 100), "")
        self.assertEqual(self.cat.mismatch(6313, 26, 80, 44), "")

    def test_an_unknown_id_is_not_treated_as_wrong(self):
        """The catalogue can be older than the realm; that is not the player's fault."""
        self.assertEqual(self.cat.mismatch(999999, 26, 80, 100), "")

    def test_a_matching_entry_has_nothing_to_say(self):
        self.assertEqual(self.cat.mismatch(4043, 26, 80, 100), "")


class LoadTests(unittest.TestCase):
    def setUp(self):
        self.dir = tempfile.mkdtemp()
        self.addCleanup(self._clean)

    def _clean(self):
        for name in os.listdir(self.dir):
            os.unlink(os.path.join(self.dir, name))
        os.rmdir(self.dir)

    def write(self, name, text):
        path = os.path.join(self.dir, name)
        with open(path, "w", encoding="utf-8") as handle:
            handle.write(text)
        return path

    def test_a_header_loads(self):
        cat = bms_coa.load(self.write("AscensionCoATalentData.h", HEADER))
        self.assertEqual(len(cat), 5)

    def test_a_json_export_loads(self):
        cat = bms_coa.load(self.write("coa.json",
                                      '[{"EntryId": 1, "ClassId": 26, "SpellIds": [5]}]'))
        self.assertEqual(len(cat), 1)

    def test_a_missing_file_says_which(self):
        with self.assertRaises(CoaError) as caught:
            bms_coa.load(os.path.join(self.dir, "absent.h"))
        self.assertIn("absent.h", str(caught.exception))

    def test_a_file_with_no_entries_is_refused_rather_than_used_empty(self):
        """An empty catalogue would silently validate nothing."""
        with self.assertRaises(CoaError):
            bms_coa.load(self.write("empty.h", "// nothing in here\n"))


if __name__ == "__main__":
    unittest.main()
